development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: db/development
  pool: 5
  username: postgres
  password:
  host: localhost


#development:
 # adapter: mysql
 # encoding: utf8
 # reconnect: false
 # database: db/development
 # pool: 5
 # username: root
 # password: 
 # socket: /opt/local/var/run/mysql5/mysqld.sock
#test:
 # adapter: mysql
  #encoding: utf8
 # reconnect: false
  #database: **myapp_test**
 # pool: 5
 # username: **root**
 # password: **supersecretpassword**
 # socket: **/opt/local/var/run/mysql5/mysqld.sock**

#production:
#  adapter: mysql
#  encoding: utf8
#  reconnect: false
 # database: **myapp_production**
 # pool: 5
  #username: **root**
 # password: **supersecretpassword**
#  socket: **/opt/local/var/run/mysql5/mysqld.sock**